# Generated by Django 4.2.4 on 2023-10-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='category',
        ),
    ]
