# Generated by Django 4.2.4 on 2023-10-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='genre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='category',
            name='borrowed_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bought_date',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.category'),
        ),
    ]
