# Generated by Django 4.2.6 on 2023-10-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_points_to_exchange_book_stock'),
        ('authentication', '0002_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books_borrowed',
            field=models.ManyToManyField(related_name='books_borrowed', to='book.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='books_bought',
            field=models.ManyToManyField(related_name='books_bought', to='book.book'),
        ),
    ]
