# Generated by Django 4.2.6 on 2023-10-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_books_borrowed_user_books_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books_borrowed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='books_bought',
        ),
    ]
