# Generated by Django 4.2.6 on 2023-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231028_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='points_to_exchange',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]