# Generated by Django 4.2.6 on 2023-10-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231028_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviews',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
