# Generated by Django 4.2.6 on 2023-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_points_to_exchange_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
