# Generated by Django 4.2.6 on 2023-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_boughtbook_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
