# Generated by Django 4.2.6 on 2023-12-10 13:06

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "books.json")


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20231210_2005'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
